version: "3.8"

services:
  github-page:
    container_name: github-page
    image: jekyll
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ../:/app
    network_mode: bridge
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve -H 0.0.0.0 -t
